export const SET_NAVIGATION_TYPES = 'SET_NAVIGATION_TYPES';
export type SET_NAVIGATION_TYPES = typeof SET_NAVIGATION_TYPES;


export const NAVIGATION_TYPES_AJAX_LOADING = 'NAVIGATION_TYPES_AJAX_LOADING';
export type NAVIGATION_TYPES_AJAX_LOADING = typeof NAVIGATION_TYPES_AJAX_LOADING;
