export const SET_NAVIGATIONS = 'SET_NAVIGATIONS';
export type SET_NAVIGATIONS = typeof SET_NAVIGATIONS;


export const NAVIGATION_AJAX_LOADING = 'NAVIGATION_AJAX_LOADING';
export type NAVIGATION_AJAX_LOADING = typeof NAVIGATION_AJAX_LOADING;
