export const SET_NAVIGATIONS = 'SET_NAVIGATIONS';
export type SET_NAVIGATIONS = typeof SET_NAVIGATIONS;

export const UPDATE_NAVIGATION = 'UPDATE_NAVIGATION';
export type UPDATE_NAVIGATION = typeof UPDATE_NAVIGATION;

export const NAVIGATIONS_AJAX_LOADING = 'NAVIGATIONS_AJAX_LOADING';
export type NAVIGATIONS_AJAX_LOADING = typeof NAVIGATIONS_AJAX_LOADING;
